from PIL import Image
import numpy as np, base64, json

P='/home/ongsalt/Programming/pjsk-score-screenshot/example/'
GW,GH=16,24

REGIONS={'score':(0.274,0.280,0.525,0.385),'highScore':(0.398,0.392,0.525,0.455),
 'perfect':(0.278,0.578,0.348,0.632),'great':(0.278,0.638,0.348,0.692),
 'good':(0.278,0.698,0.348,0.752),'bad':(0.278,0.758,0.348,0.812),
 'miss':(0.278,0.818,0.348,0.872),'combo':(0.435,0.575,0.518,0.642),
 'late':(0.368,0.748,0.415,0.795),'early':(0.466,0.748,0.503,0.795),
 'wrongWay':(0.468,0.810,0.503,0.858)}
METRIC={'late':'white','early':'white','wrongWay':'white'}

def otsu(m):
    hist,_=np.histogram(m,bins=256,range=(0,256)); tot=m.size
    s_all=(hist*np.arange(256)).sum(); wb=0; sb=0; best=(-1,128)
    for t in range(256):
        wb+=hist[t]
        if wb==0 or wb==tot: continue
        wf=tot-wb; sb+=t*hist[t]
        v=wb*wf*((sb/wb)-((s_all-sb)/wf))**2
        if v>best[0]: best=(v,t)
    return best[1]

def runs(mask):
    out=[];s=None
    for i,v in enumerate(mask):
        if v and s is None: s=i
        elif not v and s is not None: out.append((s,i));s=None
    if s is not None: out.append((s,len(mask)))
    return out

def area_resize(src, dw, dh):
    """area-average resample; identical math is implemented in digits.ts"""
    sh,sw=src.shape
    out=np.zeros((dh,dw))
    for dy in range(dh):
        y0=dy*sh/dh; y1=(dy+1)*sh/dh
        for dx in range(dw):
            x0=dx*sw/dw; x1=(dx+1)*sw/dw
            acc=0.0; wsum=0.0
            for sy in range(int(np.floor(y0)), min(sh,int(np.ceil(y1)))):
                wy=min(y1,sy+1)-max(y0,sy)
                if wy<=0: continue
                for sx in range(int(np.floor(x0)), min(sw,int(np.ceil(x1)))):
                    wx=min(x1,sx+1)-max(x0,sx)
                    if wx<=0: continue
                    acc+=src[sy,sx]*wy*wx; wsum+=wy*wx
            out[dy,dx]=acc/wsum if wsum>0 else 0
    return out

def glyphs(im,box,metric='luma'):
    W,H=im.size
    a=np.asarray(im.crop((int(box[0]*W),int(box[1]*H),int(box[2]*W),int(box[3]*H)))).astype(float)
    m=a.min(2) if metric=='white' else a@[0.299,0.587,0.114]
    t=otsu(m); b=m>t
    mx=m.max()
    ink=np.clip((m-t)/max(1.0,mx-t),0,1)*b
    rows=b.sum(1); rb=runs(rows>max(1,rows.max()*0.08))
    if not rb: return []
    y0,y1=max(rb,key=lambda r:r[1]-r[0]); h=y1-y0
    strip=b[y0:y1]; istrip=ink[y0:y1]
    out=[]
    for x0,x1 in runs(strip.sum(0)>0):
        if x1-x0<max(2,h*0.06): continue
        g=strip[:,x0:x1]; ys=np.where(g.any(1))[0]
        if len(ys)<2 or (ys[-1]-ys[0])<h*0.35: continue
        gi=istrip[ys[0]:ys[-1]+1,x0:x1]
        out.append((area_resize(gi,GW,GH).flatten(),(x1-x0)/(ys[-1]-ys[0]+1)))
    return out

def norm(v):
    v=v-v.mean(); n=np.linalg.norm(v); return v/n if n>0 else v

TRUTH={'jp':{'score':'00409596','highScore':'00517932','perfect':'1001','great':'0023','good':'0000','bad':'0000','miss':'0003','combo':'0395','late':'17','early':'6','wrongWay':'0'},
 'en':{'score':'00486051','highScore':'00843718','perfect':'1036','great':'0037','good':'0000','bad':'0000','miss':'0000','combo':'1073','late':'24','early':'13','wrongWay':'0'}}
IMS={n:Image.open(P+f).convert('RGB') for n,f in [('jp','jp_with_judgement.png'),('en','en_with_judgement.png')]}

samples={str(d):[] for d in range(10)}
for name,im in IMS.items():
    for k,box in REGIONS.items():
        gs=glyphs(im,box,METRIC.get(k,'luma')); want=TRUTH[name][k]
        assert len(gs)==len(want), f"{name} {k}: {len(gs)} vs {len(want)}"
        for (v,a),ch in zip(gs,want): samples[ch].append((v,a))

tpl={d:{'raw':np.stack([s[0] for s in ss]).mean(0),'aspect':float(np.mean([s[1] for s in ss])),'n':len(ss)} for d,ss in samples.items()}
for d in tpl: tpl[d]['v']=norm(tpl[d]['raw'])

def classify(v,a):
    vn=norm(v); best=(-9,None)
    for d,t in tpl.items():
        s=float(vn@t['v'])-0.25*abs(a-t['aspect'])
        if s>best[0]: best=(s,d)
    return best[1],best[0]

bad=0; worst=1
for name,im in IMS.items():
    for k,box in REGIONS.items():
        gs=glyphs(im,box,METRIC.get(k,'luma')); want=TRUTH[name][k]
        res=[classify(v,a) for v,a in gs]; got=''.join(r[0] for r in res)
        worst=min(worst,min(r[1] for r in res))
        if got!=want: bad+=1; print(f"WRONG {name} {k}: {got} != {want}")
print(f"area-resize round trip: {bad} failures, worst score {worst:.3f}")

if bad==0:
    lines=[]
    for d in sorted(tpl):
        q=np.clip(np.round(tpl[d]['raw']*255),0,255).astype(np.uint8)
        lines.append(f'  {{ digit: "{d}", aspect: {tpl[d]["aspect"]:.4f}, data: "{base64.b64encode(q.tobytes()).decode()}" }},')
    ts = ('// Generated by scripts/gen-digit-templates.py - do not edit by hand.\n'
          '// Mean glyph bitmaps for the Project Sekai result-screen digits, harvested from\n'
          '// example/*.png and stored as %dx%d area-averaged ink maps (uint8, row major).\n\n'
          'export const DIGIT_GRID = { width: %d, height: %d } as const;\n\n'
          'export interface DigitTemplate {\n  digit: string;\n  /** mean glyph width / height, used to tell 1 from the rest */\n  aspect: number;\n  /** base64 of %d bytes */\n  data: string;\n}\n\n'
          'export const DIGIT_TEMPLATES: DigitTemplate[] = [\n%s\n];\n') % (GW,GH,GW,GH,GW*GH,'\n'.join(lines))
    open('digit-templates.ts','w').write(ts)
    print("wrote digit-templates.ts", len(ts), "bytes; samples:", {d:tpl[d]['n'] for d in sorted(tpl)})
